spring:
  application:
    name: eureka-server
  config:
    import: optional:configserver:http://localhost:8088
  cloud:
    config:
      enabled: true
      failFast: true
      retry:
        initialInterval: 3000
        multiplier: 1.3
        maxInterval: 10000
        maxAttempts: 20
      uri: http://localhost:8088
      username: user
      password: 710680c6-93a1-4cab-b7e4-a43714e9051c
    loadbalancer:
      ribbon:
        enabled: false # Ribbon is still the default client-side loadbalancer, desable it
