node{
  stage('SCM Checkout'){
    git 'https://github.com/aaronmaj/banking-services/new/main/account-service'
  }
  stage('build package'){
    def mvnHome = tool name: 'maven-3', type: 'maven'
    sh "${mvnHome}/bin/mvn clean package}"
  }
}
