server:
  port: 8088

spring:
  profiles:
    active: native #Native sets the Spring profile associated with the backend repository (filesystem)
  cloud:
    config:
      server: #Local configuration: This locations can either of classpath or locations in the filesystem.
        #native:
          #Reads from a specific filesystem folder
          #search-locations:file://${HOME}/config-repo/spring-cloud-config
          #search-locations: classpath:/config  if the configuration files are under /resources/config folder
          #search-locations: classpath:/config
        git:
          uri: https://github.com/aaronmaj/banking-configs
          default-label: main
          search-paths: '{application}'
          #- configs*  if configuratin files are enclosed in configs like folder
          repos:
            qa:
              pattern: '*/qa'
              uri: https://github.com/aaronmaj/banking-configs-qa
              searchPaths:
                - 'configs*'
            local:
              pattern: local*
              uri: file://${HOME}/Documents/Projects/banking-configs
        encrypt:
          enabled: false # desable server side decryption

logging:
  level:
    root: info
    com.banking: debug

#Enable all Spring Boot Actuator endpoints.
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"