server:
  port: 8083
  error:
    include-message: always
  forward-headers-strategy: framework

  spring:
    jpa:
      hibernate:
        ddl-auto: update # none
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

      database: POSTGRESQL
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      defer-datasource-initialization: true
      show-sql: true
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
          use_sql_comments: true
    datasource:
      platform: postgres
      testWhileIdle: true
      validationQuery: SELECT 1
      continue-on-error: false

    database:
      driverClassName: org.postgresql.Driver

app.banking-service: localhost
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/banking_db
    username: dbtest
    password: dbtest
---
spring.config.activate.on-profile: docker
server.port: 8080
app.banking-service: service