server:
  port: 8072

spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
      #discovery.locator:
        #enabled: true  # Use the  automated routes created with the Eureka service ID
        #lowerCaseServiceId: true
      default-filters:
        - name: Retry
          args:
            retries: 3
            method: GET
            series: SERVER_ERROR
            exceptions: java.io.IOException, java.util.concurrent.TimeoutException
            backoff:
              firstBackoff: 50ms
              maxBackoff: 500ms
              factor: 2
              basedOnPreviousValue: false

      routes:
      - id: eureka-api
        uri: http://${app.eureka-server}:8761
        predicates:
        - Path=/eureka/api/{segment}
        filters:
        - SetPath=/eureka/{segment}

      - id: eureka-web-start
        uri: http://${app.eureka-server}:8761
        predicates:
        - Path=/eureka/web
        filters:
        - SetPath=/

      - id: eureka-web-other
        uri: http://${app.eureka-server}:8761
        predicates:
        - Path=/eureka/**

      - id: account-service
        uri: lb://account-service # lb:// is used to direct Spring Cloud Gateway to use the client-side load balancer to look up the destination in the discovery service.
        predicates:
        - Path=/account/**
        filters:
        - RewritePath=/account/(?<path>.*), /$\{path}
         # Allow the propagation of the authorization HTTP header remove it
        # The gateway blocks the propagation of all the three values by default: Cookie, Set-Cookie, and Authorization
        - RemoveRequestHeader= Cookie,Set-Cookie

      - id: account-service-swagger-ui
        uri: lb://account-service
        predicates:
        - Path=/openapi/**

      - id: customer-service
        uri: lb://customer-service
        predicates:
        - Path=/customer/**
        filters:
        - RewritePath=/customer/(?<path>.*), /$\{path}
        - RemoveRequestHeader= Cookie,Set-Cookie

      - id: account-service-swagger-ui
        uri: lb://customer-service
        predicates:
        - Path=/openapi/**

app.eureka-server: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE
    com.banking: DEBUG

spring.zipkin.baseUrl: http://localhost:9411
spring.sleuth.sampler.probability: 1.0
---
spring.config.activate.on-profile: docker

app.eureka-server: eureka
spring.zipkin.baseUrl: http://zipkin:9411